
[package]
name = "chem-providers"
version = "0.1.0"
edition = "2021"
authors = ["Cesar Gerardo guzman Lopez <cesar-gerardo@guzman-lopez.com>"]
description = "Crate Rust para interactuar con RDKit vía Python"
license = "MIT"
[features]
default = ["mock_rdkit"]
python = ["pyo3"]
mock_rdkit = ["mockall"]
testing = ["mock_rdkit", "mockall"]
[dependencies]
pyo3 = { version = "0.26", features = ["auto-initialize"], optional = true }
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
mockall = { version = "0.11", optional = true }
[dev-dependencies]
mockall = "0.11"
tempfile = "3.10"
