# .rustfmt.toml
indent_style = "Visual"  # O "Block"
wrap_comments = true
max_width = 125
# 2 spaces for indentation
tab_spaces = 2
hard_tabs = false
newline_style = "Unix"
use_small_heuristics = "Max"
format_strings = true
fn_call_width = 80


